server:
  port: 8084

spring:
  application:
    name: notification-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8087/eureka/