spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common
    import: optional:file:.env[.properties]
  rabbitmq:
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  application:
    name: notification-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

server:
  port: 8084

jwt:
  secret: ${JWT_SECRET}

---
spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env[.properties]

  datasource:
    url: ${LOCAL_PAYMENT_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver

secret:
  key:
    base64: ${SECRET_KEY_BASE64}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: "http://localhost:8087/eureka"
  server:
    wait-time-in-ms-when-sync-empty: 5
---
spring:
  config:
    activate:
      on-profile: prod

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${OFZ_EUREKA_URL}
  server:
    wait-time-in-ms-when-sync-empty: 5