spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common

  application:
    name: schedule-service
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: local

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: "http://localhost:8087/eureka"
  server:
    wait-time-in-ms-when-sync-empty: 5
---
spring:
  config:
    activate:
      on-profile: prod

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${OFZ_EUREKA_URL}
  server:
    wait-time-in-ms-when-sync-empty: 5