server:
  port: 8087

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${OFZ_EUREKA_URL}

  server:
    wait-time-in-ms-when-sync-empty: 5