name: dev-eureka-deploy

on:
  pull_request:
    branches: 
      - develop
    types:
      - closed
  workflow_dispatch:
      
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' 

      - name: Get PR Changed Files
        id: get-changed-files
        run: |
          git fetch origin develop
          CHANGED_FILES=$(git diff --name-only origin/develop...HEAD)
          echo "$CHANGED_FILES" | grep '^OFZ-eureka/' && echo "OFZ-eureka" >> changed_modules.txt

      - name: builde
        if: contains(steps.get-changed-files.outputs.changed_modules, 'OFZ-eureka')
        run: |
          ./gradlew :OFZ-eureka:assemble
          echo "eureka!"
  
